### ISSUE TITLE
Implement STUN server within the library

### ISSUE THREAD

**Issue by hellwolf** [noia-network/webrtc-direct#2]
- Eliminate the dependencies of public stun servers
- New parameter for server:    server = new WebRTCDirect.Server({ control_port: ..., public_ip: ... })

**Comment by l1br3** [comment]
Could you provide small doc to see what is available now and what we have to do about STUNs please ? Great library, everything works out of the box and the code is very easy to read

**Comment by Dancia** [comment]
You don't have to do anything with STUN's out of the box, except if you face issues. In that case let maintainers know, we will do our best solving it.

Currently I have very limited time for this library. I'll update docs once I'm available. There is not much missing. I think main points missing in docs/issues:
- Limited IPv6 support (still need to put some more work)
- WebRTC Direct Client can both run in browser and in NodeJS environment (needs wrtc library injected to wrok in NodeJS)
- WebRTC Direct Client can pick wrong candidate (observer in NodeJS environment if many network interfaces exist), so parameter `candidateIp` can help to set correct one.

As I mentioned, I'll update docs once I have more free time. Thanks for feedback!
